AWSTemplateFormatVersion: '2010-09-09'
Description: Main stack for EC2, Lambda, Roles

Parameters:
  AMIId:
    Type: String
    Default: ami-0c02fb55956c7d316
    Description: The AMI ID to use for the EC2 instance
  KeyPairName:
    Type: String
    Default: your-key-name
    Description: The name of the EC2 Key Pair
  InstanceType:
    Type: String
    Default: t3.micro
    Description: EC2 instance type

Resources:
  IAMRolesStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./roles.yml
  
  LambdaStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: IAMRolesStack
    Properties:
      TemplateURL: ./lambda-deploy.yml

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref AMIId
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyPairName
      SecurityGroups:
        - !Ref EC2SecurityGroup
      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          systemctl enable httpd
          systemctl start httpd
          echo "<html><h1>Hello from EC2!</h1></html>" > /var/www/html/index.html

  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
